name: 'Setup'
description: 'Sets up dependencies for project'
inputs:
  GITHUB_TOKEN:
    required: true
    description: GitHub PAT for npm registry
  TEST_INPUT:
    required: true
    description: Only a test, remove me

runs:
  using: 'composite'
  steps:
    - name: Use pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'pnpm'
        scope: '@skf-internal'

    - name: Setup private NPM repositories
      shell: bash
      run: |
        echo "@skf:registry=https://npm.pkg.github.com" > ~/.npmrc
        echo "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN" >> ~/.npmrc
      env:
        GITHUB_TOKEN: '${{ inputs.GITHUB_TOKEN }}'

    - name: Test echo step
      shell: bash
      run: |
        cat ~/.npmrc

    - name: Install dependencies
      shell: bash
      run: pnpm install
      env:
        NPM_TOKEN: ${{ inputs.GITHUB_TOKEN }}
