name: Unit Tests on PR

on:
  pull_request:
    branches: ['main']
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    name: Setup
    uses: ./.github/workflows/setup.yml

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - run: pnpm test
