name: Unit Tests on PR

on:
  pull_request:
    branches: ['main']
jobs:
  setup:
    name: Setup
    uses: ./.github/workflows/setup.yml

  test:
    runs-on: ubuntu-latest
    needs: [setup]
    name: Test
    steps:
      - run: pnpm test
