name: Setup

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        uses: ./.github/workflows/setup/action.yml
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
