name: Setup

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        uses: ./.github/workflows/setup.yml
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Authenticate private npm repos
        shell: bash
        run: echo "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN" > $NPM_CONFIG_USERCONFIG
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - name: Install dependencies
        run: pnpm install
