name: Setup

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Use pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Authenticate private npm repos
        shell: bash
        run: echo "//npm.pkg.github.com/:_authToken=${{secrets.GITHUB_TOKEN}}" > $NPM_CONFIG_USERCONFIG

      - name: Install dependencies
        run: pnpm install
